/**
 * Infrastructure as Code Step Component
 * Configure Terraform modules, GitOps workflows, state backend, and workspaces
 */

import React, { useCallback, useState, useMemo, useEffect } from 'react';
import {
  Box,
  Typography,
  Paper,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  FormControlLabel,
  Switch,
  Chip,
  IconButton,
  Button,
  List,
  ListItem,
  ListItemText,
  ListItemSecondaryAction,
  Alert,
  Grid,
  Divider,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Tabs,
  Tab,
  Tooltip,
} from '@mui/material';
import {
  ExpandMore as ExpandMoreIcon,
  Delete as DeleteIcon,
  Add as AddIcon,
  Edit as EditIcon,
  Code as CodeIcon,
  CloudSync as GitOpsIcon,
  Storage as StateIcon,
  Layers as WorkspaceIcon,
  Download as DownloadIcon,
  Refresh as RefreshIcon,
} from '@mui/icons-material';
import { v4 as uuid } from 'uuid';
import {
  IaCConfig,
  TerraformModule,
  WorkspaceConfig,
  GitOpsProvider,
  StateBackend,
  DevOpsLayerData,
  GITOPS_PROVIDERS,
  STATE_BACKENDS,
} from '../../../../../types/devops';
import { ValidationError, NetworkLayerData } from '../../../../../types/network';

interface InfrastructureAsCodeStepProps {
  iac: IaCConfig;
  onChange: (config: IaCConfig) => void;
  devopsData: DevOpsLayerData;
  networkData?: NetworkLayerData;
  platformData?: Record<string, unknown>;
  errors: ValidationError[];
}

// Terraform code preview tabs
interface TabPanelProps {
  children?: React.ReactNode;
  index: number;
  value: number;
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props;
  return (
    <div
      role="tabpanel"
      hidden={value !== index}
      id={`terraform-tabpanel-${index}`}
      aria-labelledby={`terraform-tab-${index}`}
      {...other}
    >
      {value === index && <Box sx={{ p: 2 }}>{children}</Box>}
    </div>
  );
}

export function InfrastructureAsCodeStep({
  iac,
  onChange,
  devopsData,
  networkData,
  platformData,
  errors,
}: InfrastructureAsCodeStepProps) {
  const [expandedPanel, setExpandedPanel] = useState<string | false>('modules');
  const [workspaceDialogOpen, setWorkspaceDialogOpen] = useState(false);
  const [editingWorkspace, setEditingWorkspace] = useState<WorkspaceConfig | null>(null);
  const [previewTab, setPreviewTab] = useState(0);
  const [generatingModules, setGeneratingModules] = useState(false);

  const handlePanelChange = (panel: string) => (_event: React.SyntheticEvent, isExpanded: boolean) => {
    setExpandedPanel(isExpanded ? panel : false);
  };

  // Generate Terraform modules from configuration
  const generateModules = useCallback(() => {
    setGeneratingModules(true);

    const modules: TerraformModule[] = [];

    // Network Module
    if (networkData) {
      const networkVars = [
        { name: 'vpc_name', type: 'string', description: 'Name of the VPC', default: networkData.vpc?.name, sensitive: false },
        { name: 'vpc_cidr', type: 'string', description: 'CIDR block for the VPC', default: networkData.vpc?.cidrBlock, sensitive: false },
        { name: 'environment', type: 'string', description: 'Environment name', default: 'dev', sensitive: false },
      ];

      const networkContent = `# Network Module - Generated by Infrastructure Designer
# VPC: ${networkData.vpc?.name || 'unnamed'}

resource "aws_vpc" "main" {
  cidr_block           = var.vpc_cidr
  enable_dns_support   = ${networkData.vpc?.enableDnsSupport ?? true}
  enable_dns_hostnames = ${networkData.vpc?.enableDnsHostnames ?? true}

  tags = {
    Name        = var.vpc_name
    Environment = var.environment
    ManagedBy   = "terraform"
  }
}

${networkData.subnets?.map((subnet, i) => `
resource "aws_subnet" "${subnet.name.replace(/[^a-zA-Z0-9_]/g, '_')}" {
  vpc_id                  = aws_vpc.main.id
  cidr_block              = "${subnet.cidrBlock}"
  availability_zone       = "${subnet.availabilityZone}"
  map_public_ip_on_launch = ${subnet.isPublic}

  tags = {
    Name        = "${subnet.name}"
    Environment = var.environment
    Type        = "${subnet.isPublic ? 'public' : 'private'}"
  }
}
`).join('\n') || '# No subnets configured'}

${networkData.routing?.internetGateway?.enabled ? `
resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id

  tags = {
    Name        = "${networkData.routing.internetGateway.name || 'main-igw'}"
    Environment = var.environment
  }
}
` : '# Internet Gateway not enabled'}
`;

      modules.push({
        name: 'network',
        path: 'modules/network',
        version: '1.0.0',
        source: 'local',
        variables: networkVars,
        outputs: [
          { name: 'vpc_id', description: 'The ID of the VPC', value: 'aws_vpc.main.id', sensitive: false },
          { name: 'vpc_cidr', description: 'The CIDR block of the VPC', value: 'aws_vpc.main.cidr_block', sensitive: false },
        ],
        content: networkContent,
        dependencies: [],
      });
    }

    // CI/CD Module
    if (devopsData.cicd) {
      const cicdContent = `# CI/CD Module - Generated by Infrastructure Designer
# Source Control: ${devopsData.cicd.sourceControl.provider}
# Repository: ${devopsData.cicd.sourceControl.repositoryUrl}

# CodePipeline
resource "aws_codepipeline" "main" {
  name     = "\${var.project_name}-pipeline"
  role_arn = aws_iam_role.codepipeline.arn

  artifact_store {
    location = aws_s3_bucket.artifacts.id
    type     = "S3"
  }

  stage {
    name = "Source"
    action {
      name             = "Source"
      category         = "Source"
      owner            = "AWS"
      provider         = "CodeStarSourceConnection"
      version          = "1"
      output_artifacts = ["source_output"]

      configuration = {
        ConnectionArn    = aws_codestarconnections_connection.github.arn
        FullRepositoryId = "${devopsData.cicd.sourceControl.repositoryUrl.replace('https://github.com/', '')}"
        BranchName       = "${devopsData.cicd.sourceControl.defaultBranch}"
      }
    }
  }

${devopsData.cicd.buildPipeline.stages.filter(s => s.enabled).map((stage, i) => `
  stage {
    name = "${stage.name}"
    action {
      name            = "${stage.name}"
      category        = "${stage.type === 'build' ? 'Build' : stage.type === 'deploy' ? 'Deploy' : 'Build'}"
      owner           = "AWS"
      provider        = "CodeBuild"
      version         = "1"
      input_artifacts = ${i === 0 ? '["source_output"]' : '["build_output"]'}
      ${stage.type !== 'deploy' ? 'output_artifacts = ["build_output"]' : ''}

      configuration = {
        ProjectName = aws_codebuild_project.${stage.id}.name
      }
    }
  }
`).join('\n')}
}

# Artifact S3 Bucket
resource "aws_s3_bucket" "artifacts" {
  bucket = "\${var.project_name}-artifacts-\${data.aws_caller_identity.current.account_id}"

  tags = {
    Name        = "\${var.project_name}-artifacts"
    Environment = var.environment
  }
}

# CodeBuild Projects
${devopsData.cicd.buildPipeline.stages.filter(s => s.enabled).map(stage => `
resource "aws_codebuild_project" "${stage.id}" {
  name         = "\${var.project_name}-${stage.name.toLowerCase().replace(/\s+/g, '-')}"
  service_role = aws_iam_role.codebuild.arn

  artifacts {
    type = "CODEPIPELINE"
  }

  environment {
    compute_type                = "BUILD_GENERAL1_SMALL"
    image                       = "aws/codebuild/standard:7.0"
    type                        = "LINUX_CONTAINER"
    privileged_mode             = true
    image_pull_credentials_type = "CODEBUILD"
  }

  source {
    type      = "CODEPIPELINE"
    buildspec = "buildspec-${stage.name.toLowerCase()}.yml"
  }

  logs_config {
    cloudwatch_logs {
      group_name = "/aws/codebuild/\${var.project_name}"
      stream_name = "${stage.name.toLowerCase()}"
    }
  }
}
`).join('\n')}
`;

      modules.push({
        name: 'cicd',
        path: 'modules/cicd',
        version: '1.0.0',
        source: 'local',
        variables: [
          { name: 'project_name', type: 'string', description: 'Name of the project', default: undefined, sensitive: false },
          { name: 'environment', type: 'string', description: 'Environment name', default: 'dev', sensitive: false },
        ],
        outputs: [
          { name: 'pipeline_arn', description: 'ARN of the CodePipeline', value: 'aws_codepipeline.main.arn', sensitive: false },
        ],
        content: cicdContent,
        dependencies: ['network'],
      });
    }

    // Monitoring Module
    if (devopsData.monitoring) {
      const monitoringContent = `# Monitoring Module - Generated by Infrastructure Designer
# Log Groups: ${devopsData.monitoring.logGroups.length}
# Alarms: ${devopsData.monitoring.alarms.length}

${devopsData.monitoring.logGroups.map(lg => `
resource "aws_cloudwatch_log_group" "${lg.serviceName.replace(/[^a-zA-Z0-9_]/g, '_')}" {
  name              = "${lg.name}"
  retention_in_days = ${lg.retentionDays}

  tags = {
    Service     = "${lg.serviceName}"
    Environment = var.environment
  }
}
`).join('\n')}

${devopsData.monitoring.alarms.filter(a => a.enabled).map(alarm => `
resource "aws_cloudwatch_metric_alarm" "${alarm.name.replace(/[^a-zA-Z0-9_]/g, '_')}" {
  alarm_name          = "${alarm.name}"
  alarm_description   = "${alarm.description}"
  comparison_operator = "${alarm.comparisonOperator}"
  evaluation_periods  = ${alarm.evaluationPeriods}
  metric_name         = "${alarm.metricName}"
  namespace           = "${alarm.metricNamespace}"
  period              = ${alarm.period}
  statistic           = "${alarm.statistic}"
  threshold           = ${alarm.threshold}

  tags = {
    Environment = var.environment
  }
}
`).join('\n')}

${devopsData.monitoring.dashboards.map(dashboard => `
resource "aws_cloudwatch_dashboard" "${dashboard.name.replace(/[^a-zA-Z0-9_]/g, '_')}" {
  dashboard_name = "${dashboard.name}"
  dashboard_body = jsonencode({
    widgets = ${JSON.stringify(dashboard.widgets.map(w => ({
      type: w.type === 'metric' ? 'metric' : w.type,
      x: w.x,
      y: w.y,
      width: w.width,
      height: w.height,
      properties: {
        title: w.title,
        ...w.properties
      }
    })), null, 2)}
  })
}
`).join('\n')}
`;

      modules.push({
        name: 'monitoring',
        path: 'modules/monitoring',
        version: '1.0.0',
        source: 'local',
        variables: [
          { name: 'environment', type: 'string', description: 'Environment name', default: 'dev', sensitive: false },
        ],
        outputs: [],
        content: monitoringContent,
        dependencies: [],
      });
    }

    onChange({
      ...iac,
      modules,
    });

    setTimeout(() => setGeneratingModules(false), 500);
  }, [networkData, devopsData, iac, onChange]);

  // Auto-generate modules on first render if empty
  useEffect(() => {
    if (iac.modules.length === 0 && networkData) {
      generateModules();
    }
  }, []);

  // State Backend handlers
  const handleStateBackendChange = useCallback(
    (field: keyof IaCConfig['stateBackend'], value: unknown) => {
      onChange({
        ...iac,
        stateBackend: {
          ...iac.stateBackend,
          [field]: value,
        },
      });
    },
    [iac, onChange]
  );

  // GitOps handlers
  const handleGitOpsChange = useCallback(
    (field: keyof IaCConfig['gitOps'], value: unknown) => {
      onChange({
        ...iac,
        gitOps: {
          ...iac.gitOps,
          [field]: value,
        },
      });
    },
    [iac, onChange]
  );

  // Workspace handlers
  const handleAddWorkspace = useCallback(() => {
    const newWorkspace: WorkspaceConfig = {
      name: '',
      environment: 'dev',
      variables: {},
      tfvarsFile: '',
      autoApply: false,
    };
    setEditingWorkspace(newWorkspace);
    setWorkspaceDialogOpen(true);
  }, []);

  const handleSaveWorkspace = useCallback(
    (workspace: WorkspaceConfig) => {
      const exists = iac.workspaces.find((w) => w.name === workspace.name);
      if (exists) {
        onChange({
          ...iac,
          workspaces: iac.workspaces.map((w) =>
            w.name === workspace.name ? workspace : w
          ),
        });
      } else {
        onChange({
          ...iac,
          workspaces: [...iac.workspaces, workspace],
        });
      }
      setWorkspaceDialogOpen(false);
      setEditingWorkspace(null);
    },
    [iac, onChange]
  );

  const handleDeleteWorkspace = useCallback(
    (name: string) => {
      onChange({
        ...iac,
        workspaces: iac.workspaces.filter((w) => w.name !== name),
      });
    },
    [iac, onChange]
  );

  // Get errors for specific paths
  const getFieldErrors = (path: string) =>
    errors.filter((e) => e.path?.includes(path));

  // Generate backend.tf content
  const backendContent = useMemo(() => {
    if (iac.stateBackend.type === 's3') {
      return `# Terraform Backend Configuration
terraform {
  backend "s3" {
    bucket         = "${iac.stateBackend.bucket || 'my-terraform-state'}"
    key            = "${iac.stateBackend.key || 'terraform.tfstate'}"
    region         = "${iac.stateBackend.region || 'us-east-1'}"
    dynamodb_table = "${iac.stateBackend.dynamoDbTable || 'terraform-locks'}"
    encrypt        = ${iac.stateBackend.encrypt}
  }

  required_providers {
${iac.requiredProviders.map(p => `    ${p.name} = {
      source  = "${p.source}"
      version = "${p.version}"
    }`).join('\n')}
  }

  required_version = ">= ${iac.terraformVersion}"
}`;
    }
    return `# Local Backend (not recommended for production)
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
}`;
  }, [iac.stateBackend, iac.terraformVersion, iac.requiredProviders]);

  // Generate GitHub Actions workflow
  const workflowContent = useMemo(() => {
    if (iac.gitOps.provider === 'github-actions') {
      return `# Terraform GitHub Actions Workflow
# Generated by Infrastructure Designer

name: Terraform

on:
  push:
    branches: [${devopsData.cicd.sourceControl.productionBranch || 'main'}]
  pull_request:
    branches: [${devopsData.cicd.sourceControl.productionBranch || 'main'}]

permissions:
  contents: read
  pull-requests: write

env:
  TF_VERSION: "${iac.terraformVersion}"
  AWS_REGION: "${iac.stateBackend.region || 'us-east-1'}"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: \${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: \${{ secrets.AWS_ROLE_ARN }}
          aws-region: \${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - name: Terraform Apply
        if: github.ref == 'refs/heads/${devopsData.cicd.sourceControl.productionBranch || 'main'}' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
${iac.gitOps.approvalRequired ? `
  production:
    name: Production Deployment
    needs: terraform
    runs-on: ubuntu-latest
    environment: production
    if: github.ref == 'refs/heads/${devopsData.cicd.sourceControl.productionBranch || 'main'}'

    steps:
      - name: Deploy to Production
        run: echo "Deploying to production..."
` : ''}`;
    }
    return '# GitOps workflow not configured for this provider';
  }, [iac.gitOps, iac.terraformVersion, iac.stateBackend.region, devopsData.cicd.sourceControl.productionBranch]);

  return (
    <Box>
      <Typography variant="h6" gutterBottom>
        Infrastructure as Code
      </Typography>
      <Typography variant="body2" color="text.secondary" sx={{ mb: 3 }}>
        Configure Terraform modules, GitOps workflows, and state management.
      </Typography>

      {errors.filter((e) => e.severity === 'error').length > 0 && (
        <Alert severity="error" sx={{ mb: 2 }}>
          {errors.filter((e) => e.severity === 'error').length} configuration error(s) found.
        </Alert>
      )}

      {/* Terraform Modules Section */}
      <Accordion
        expanded={expandedPanel === 'modules'}
        onChange={handlePanelChange('modules')}
      >
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <CodeIcon />
            <Typography>Terraform Modules</Typography>
            <Chip
              size="small"
              label={`${iac.modules.length} modules`}
              color="primary"
              variant="outlined"
            />
          </Box>
        </AccordionSummary>
        <AccordionDetails>
          <Box sx={{ mb: 2 }}>
            <Button
              variant="outlined"
              startIcon={<RefreshIcon />}
              onClick={generateModules}
              disabled={generatingModules}
            >
              {generatingModules ? 'Generating...' : 'Regenerate Modules'}
            </Button>
          </Box>

          {iac.modules.length === 0 ? (
            <Alert severity="info">
              No modules generated yet. Click "Regenerate Modules" to create Terraform modules from your configuration.
            </Alert>
          ) : (
            <Box>
              <Tabs value={previewTab} onChange={(_, v) => setPreviewTab(v)}>
                {iac.modules.map((module, i) => (
                  <Tab key={module.name} label={module.name} id={`terraform-tab-${i}`} />
                ))}
                <Tab label="backend.tf" id="terraform-tab-backend" />
                <Tab label="workflow" id="terraform-tab-workflow" />
              </Tabs>
              {iac.modules.map((module, i) => (
                <TabPanel key={module.name} value={previewTab} index={i}>
                  <Paper
                    variant="outlined"
                    sx={{
                      p: 2,
                      bgcolor: 'grey.900',
                      color: 'grey.100',
                      fontFamily: 'monospace',
                      fontSize: '0.85rem',
                      overflow: 'auto',
                      maxHeight: 400,
                      whiteSpace: 'pre-wrap',
                    }}
                  >
                    {module.content}
                  </Paper>
                </TabPanel>
              ))}
              <TabPanel value={previewTab} index={iac.modules.length}>
                <Paper
                  variant="outlined"
                  sx={{
                    p: 2,
                    bgcolor: 'grey.900',
                    color: 'grey.100',
                    fontFamily: 'monospace',
                    fontSize: '0.85rem',
                    overflow: 'auto',
                    maxHeight: 400,
                    whiteSpace: 'pre-wrap',
                  }}
                >
                  {backendContent}
                </Paper>
              </TabPanel>
              <TabPanel value={previewTab} index={iac.modules.length + 1}>
                <Paper
                  variant="outlined"
                  sx={{
                    p: 2,
                    bgcolor: 'grey.900',
                    color: 'grey.100',
                    fontFamily: 'monospace',
                    fontSize: '0.85rem',
                    overflow: 'auto',
                    maxHeight: 400,
                    whiteSpace: 'pre-wrap',
                  }}
                >
                  {workflowContent}
                </Paper>
              </TabPanel>
            </Box>
          )}
        </AccordionDetails>
      </Accordion>

      {/* State Backend Section */}
      <Accordion
        expanded={expandedPanel === 'state'}
        onChange={handlePanelChange('state')}
      >
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <StateIcon />
            <Typography>State Backend</Typography>
            <Chip
              size="small"
              label={iac.stateBackend.type}
              color={iac.stateBackend.type === 'local' ? 'warning' : 'primary'}
              variant="outlined"
            />
          </Box>
        </AccordionSummary>
        <AccordionDetails>
          <Grid container spacing={2}>
            <Grid item xs={12} md={6}>
              <FormControl fullWidth size="small">
                <InputLabel>Backend Type</InputLabel>
                <Select
                  value={iac.stateBackend.type}
                  label="Backend Type"
                  onChange={(e) => handleStateBackendChange('type', e.target.value as StateBackend)}
                >
                  {STATE_BACKENDS.map((b) => (
                    <MenuItem key={b.value} value={b.value}>
                      <Box>
                        <Typography variant="body2">{b.label}</Typography>
                        <Typography variant="caption" color="text.secondary">
                          {b.description}
                        </Typography>
                      </Box>
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>

            {iac.stateBackend.type === 's3' && (
              <>
                <Grid item xs={12} md={6}>
                  <TextField
                    fullWidth
                    size="small"
                    label="S3 Bucket"
                    value={iac.stateBackend.bucket || ''}
                    onChange={(e) => handleStateBackendChange('bucket', e.target.value)}
                    error={getFieldErrors('bucket').length > 0}
                    helperText={getFieldErrors('bucket')[0]?.message}
                  />
                </Grid>
                <Grid item xs={12} md={6}>
                  <TextField
                    fullWidth
                    size="small"
                    label="State Key"
                    value={iac.stateBackend.key || ''}
                    onChange={(e) => handleStateBackendChange('key', e.target.value)}
                    placeholder="path/to/terraform.tfstate"
                  />
                </Grid>
                <Grid item xs={12} md={6}>
                  <TextField
                    fullWidth
                    size="small"
                    label="Region"
                    value={iac.stateBackend.region || ''}
                    onChange={(e) => handleStateBackendChange('region', e.target.value)}
                  />
                </Grid>
                <Grid item xs={12} md={6}>
                  <TextField
                    fullWidth
                    size="small"
                    label="DynamoDB Lock Table"
                    value={iac.stateBackend.dynamoDbTable || ''}
                    onChange={(e) => handleStateBackendChange('dynamoDbTable', e.target.value)}
                    error={getFieldErrors('dynamoDbTable').length > 0}
                    helperText={getFieldErrors('dynamoDbTable')[0]?.message || 'Required for state locking'}
                  />
                </Grid>
                <Grid item xs={12}>
                  <FormControlLabel
                    control={
                      <Switch
                        checked={iac.stateBackend.encrypt}
                        onChange={(e) => handleStateBackendChange('encrypt', e.target.checked)}
                      />
                    }
                    label="Enable Server-Side Encryption"
                  />
                </Grid>
              </>
            )}
          </Grid>
        </AccordionDetails>
      </Accordion>

      {/* GitOps Section */}
      <Accordion
        expanded={expandedPanel === 'gitops'}
        onChange={handlePanelChange('gitops')}
      >
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <GitOpsIcon />
            <Typography>GitOps Workflow</Typography>
            <Chip
              size="small"
              label={GITOPS_PROVIDERS.find((p) => p.value === iac.gitOps.provider)?.label || iac.gitOps.provider}
              color="primary"
              variant="outlined"
            />
          </Box>
        </AccordionSummary>
        <AccordionDetails>
          <Grid container spacing={2}>
            <Grid item xs={12} md={6}>
              <FormControl fullWidth size="small">
                <InputLabel>GitOps Provider</InputLabel>
                <Select
                  value={iac.gitOps.provider}
                  label="GitOps Provider"
                  onChange={(e) => handleGitOpsChange('provider', e.target.value as GitOpsProvider)}
                >
                  {GITOPS_PROVIDERS.map((p) => (
                    <MenuItem key={p.value} value={p.value}>
                      {p.label}
                    </MenuItem>
                  ))}
                </Select>
              </FormControl>
            </Grid>
            <Grid item xs={12} md={6}>
              <TextField
                fullWidth
                size="small"
                label="Workflow Path"
                value={iac.gitOps.workflowPath}
                onChange={(e) => handleGitOpsChange('workflowPath', e.target.value)}
                error={getFieldErrors('workflowPath').length > 0}
                helperText={getFieldErrors('workflowPath')[0]?.message}
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <FormControlLabel
                control={
                  <Switch
                    checked={iac.gitOps.planOnPR}
                    onChange={(e) => handleGitOpsChange('planOnPR', e.target.checked)}
                  />
                }
                label="Run Plan on Pull Requests"
              />
            </Grid>
            <Grid item xs={12} md={6}>
              <FormControlLabel
                control={
                  <Switch
                    checked={iac.gitOps.applyOnMerge}
                    onChange={(e) => handleGitOpsChange('applyOnMerge', e.target.checked)}
                  />
                }
                label="Auto-Apply on Merge"
              />
            </Grid>
            <Grid item xs={12}>
              <FormControlLabel
                control={
                  <Switch
                    checked={iac.gitOps.approvalRequired}
                    onChange={(e) => handleGitOpsChange('approvalRequired', e.target.checked)}
                  />
                }
                label="Require Approval for Production"
              />
            </Grid>
            <Grid item xs={12}>
              <FormControlLabel
                control={
                  <Switch
                    checked={iac.gitOps.driftDetection}
                    onChange={(e) => handleGitOpsChange('driftDetection', e.target.checked)}
                  />
                }
                label="Enable Drift Detection"
              />
            </Grid>
            {iac.gitOps.driftDetection && (
              <Grid item xs={12} md={6}>
                <TextField
                  fullWidth
                  size="small"
                  label="Drift Detection Schedule (cron)"
                  value={iac.gitOps.driftSchedule}
                  onChange={(e) => handleGitOpsChange('driftSchedule', e.target.value)}
                  placeholder="0 0 * * *"
                  helperText="Daily at midnight by default"
                />
              </Grid>
            )}
          </Grid>
        </AccordionDetails>
      </Accordion>

      {/* Workspaces Section */}
      <Accordion
        expanded={expandedPanel === 'workspaces'}
        onChange={handlePanelChange('workspaces')}
      >
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
            <WorkspaceIcon />
            <Typography>Workspaces</Typography>
            <Chip
              size="small"
              label={`${iac.workspaces.length} configured`}
              color="primary"
              variant="outlined"
            />
          </Box>
        </AccordionSummary>
        <AccordionDetails>
          <Box sx={{ mb: 2 }}>
            <Button
              variant="outlined"
              startIcon={<AddIcon />}
              onClick={handleAddWorkspace}
            >
              Add Workspace
            </Button>
          </Box>

          {iac.workspaces.length === 0 ? (
            <Alert severity="warning">
              No workspaces configured. Add workspaces for different environments (dev, staging, prod).
            </Alert>
          ) : (
            <Grid container spacing={2}>
              {iac.workspaces.map((ws) => (
                <Grid item xs={12} md={4} key={ws.name}>
                  <Paper variant="outlined" sx={{ p: 2 }}>
                    <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <Box>
                        <Typography variant="subtitle2">{ws.name}</Typography>
                        <Chip
                          size="small"
                          label={ws.environment}
                          color={ws.environment === 'prod' ? 'error' : ws.environment === 'staging' ? 'warning' : 'success'}
                          variant="outlined"
                          sx={{ mt: 0.5 }}
                        />
                      </Box>
                      <Box>
                        <IconButton
                          size="small"
                          onClick={() => {
                            setEditingWorkspace(ws);
                            setWorkspaceDialogOpen(true);
                          }}
                        >
                          <EditIcon fontSize="small" />
                        </IconButton>
                        <IconButton
                          size="small"
                          onClick={() => handleDeleteWorkspace(ws.name)}
                          disabled={iac.workspaces.length <= 1}
                        >
                          <DeleteIcon fontSize="small" />
                        </IconButton>
                      </Box>
                    </Box>
                    <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1 }}>
                      Auto-apply: {ws.autoApply ? 'Yes' : 'No'}
                    </Typography>
                    {ws.tfvarsFile && (
                      <Typography variant="caption" color="text.secondary" display="block">
                        Variables: {ws.tfvarsFile}
                      </Typography>
                    )}
                  </Paper>
                </Grid>
              ))}
            </Grid>
          )}
        </AccordionDetails>
      </Accordion>

      {/* Warnings */}
      {errors.filter((e) => e.severity === 'warning').length > 0 && (
        <Alert severity="warning" sx={{ mt: 2 }}>
          <Typography variant="subtitle2">Warnings:</Typography>
          <ul style={{ margin: 0, paddingLeft: 20 }}>
            {errors
              .filter((e) => e.severity === 'warning')
              .map((e, i) => (
                <li key={i}>{e.message}</li>
              ))}
          </ul>
        </Alert>
      )}

      {/* Workspace Dialog */}
      <Dialog
        open={workspaceDialogOpen}
        onClose={() => {
          setWorkspaceDialogOpen(false);
          setEditingWorkspace(null);
        }}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>
          {editingWorkspace && iac.workspaces.find((w) => w.name === editingWorkspace.name)
            ? 'Edit Workspace'
            : 'Add Workspace'}
        </DialogTitle>
        <DialogContent>
          {editingWorkspace && (
            <Grid container spacing={2} sx={{ mt: 1 }}>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  size="small"
                  label="Workspace Name"
                  value={editingWorkspace.name}
                  onChange={(e) =>
                    setEditingWorkspace({ ...editingWorkspace, name: e.target.value })
                  }
                />
              </Grid>
              <Grid item xs={12}>
                <FormControl fullWidth size="small">
                  <InputLabel>Environment</InputLabel>
                  <Select
                    value={editingWorkspace.environment}
                    label="Environment"
                    onChange={(e) =>
                      setEditingWorkspace({
                        ...editingWorkspace,
                        environment: e.target.value as 'dev' | 'staging' | 'prod',
                      })
                    }
                  >
                    <MenuItem value="dev">Development</MenuItem>
                    <MenuItem value="staging">Staging</MenuItem>
                    <MenuItem value="prod">Production</MenuItem>
                  </Select>
                </FormControl>
              </Grid>
              <Grid item xs={12}>
                <TextField
                  fullWidth
                  size="small"
                  label="Variables File"
                  value={editingWorkspace.tfvarsFile}
                  onChange={(e) =>
                    setEditingWorkspace({ ...editingWorkspace, tfvarsFile: e.target.value })
                  }
                  placeholder="dev.tfvars"
                />
              </Grid>
              <Grid item xs={12}>
                <FormControlLabel
                  control={
                    <Switch
                      checked={editingWorkspace.autoApply}
                      onChange={(e) =>
                        setEditingWorkspace({
                          ...editingWorkspace,
                          autoApply: e.target.checked,
                        })
                      }
                    />
                  }
                  label="Auto-Apply Changes"
                />
                {editingWorkspace.environment === 'prod' && editingWorkspace.autoApply && (
                  <Alert severity="warning" sx={{ mt: 1 }}>
                    Auto-apply is not recommended for production environments.
                  </Alert>
                )}
              </Grid>
            </Grid>
          )}
        </DialogContent>
        <DialogActions>
          <Button
            onClick={() => {
              setWorkspaceDialogOpen(false);
              setEditingWorkspace(null);
            }}
          >
            Cancel
          </Button>
          <Button
            variant="contained"
            onClick={() => editingWorkspace && handleSaveWorkspace(editingWorkspace)}
            disabled={!editingWorkspace?.name}
          >
            Save
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}

export default InfrastructureAsCodeStep;
