/**
 * NetworkValidationStep Component
 * Step 5 of Network Wizard - Validate and review configuration
 */

import React, { useCallback, useMemo, useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Paper,
  Button,
  Alert,
  AlertTitle,
  List,
  ListItem,
  ListItemIcon,
  ListItemText,
  Chip,
  Divider,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Table,
  TableBody,
  TableCell,
  TableRow,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  IconButton,
  Tooltip,
  CircularProgress,
} from '@mui/material';
import {
  CheckCircle as SuccessIcon,
  Error as ErrorIcon,
  Warning as WarningIcon,
  Info as InfoIcon,
  ExpandMore as ExpandMoreIcon,
  Code as CodeIcon,
  ContentCopy as CopyIcon,
  Build as FixIcon,
  Refresh as RefreshIcon,
} from '@mui/icons-material';
import {
  NetworkLayerData,
  ValidationResult,
  ValidationError,
} from '../../../../../types/network';
import { validateNetworkLayer } from '../../utils/validation';
import { calculateAvailableIPs } from '../../utils/cidr';
import { estimateNATCost } from '../../utils/constants';

export interface NetworkValidationStepProps {
  vpc: NetworkLayerData['vpc'];
  subnets: NetworkLayerData['subnets'];
  routing: NetworkLayerData['routing'];
  securityGroups: NetworkLayerData['securityGroups'];
  onFix?: (error: ValidationError) => void;
  onValidationComplete?: (result: ValidationResult) => void;
}

export function NetworkValidationStep({
  vpc,
  subnets,
  routing,
  securityGroups,
  onFix,
  onValidationComplete,
}: NetworkValidationStepProps) {
  const [isValidating, setIsValidating] = useState(false);
  const [terraformDialogOpen, setTerraformDialogOpen] = useState(false);
  const [copied, setCopied] = useState(false);

  // Run validation
  const validationResult = useMemo(() => {
    const data: NetworkLayerData = { vpc, subnets, routing, securityGroups };
    return validateNetworkLayer(data);
  }, [vpc, subnets, routing, securityGroups]);

  // Notify parent of validation result
  useEffect(() => {
    if (onValidationComplete) {
      onValidationComplete(validationResult);
    }
  }, [validationResult, onValidationComplete]);

  // Calculate summary stats
  const stats = useMemo(() => {
    const publicSubnets = subnets.filter((s) => s.isPublic);
    const privateSubnets = subnets.filter((s) => !s.isPublic);
    const totalIPs = subnets.reduce(
      (sum, s) => sum + calculateAvailableIPs(s.cidrBlock, true),
      0
    );
    const natCost = estimateNATCost(routing.natGateways.length);

    return {
      vpcCidr: vpc.cidrBlock,
      totalSubnets: subnets.length,
      publicSubnets: publicSubnets.length,
      privateSubnets: privateSubnets.length,
      totalIPs,
      hasIGW: routing.internetGateway.enabled,
      natCount: routing.natGateways.length,
      sgCount: securityGroups.length,
      ruleCount: securityGroups.reduce(
        (sum, sg) => sum + sg.ingressRules.length + sg.egressRules.length,
        0
      ),
      estimatedCost: natCost.monthly,
    };
  }, [vpc, subnets, routing, securityGroups]);

  // Generate Terraform preview
  const terraformCode = useMemo(() => {
    const lines: string[] = [
      '# Generated by Network Architect Wizard',
      '# This is a preview - actual deployment will generate complete Terraform',
      '',
      '# VPC',
      `resource "aws_vpc" "${vpc.name.replace(/-/g, '_')}" {`,
      `  cidr_block           = "${vpc.cidrBlock}"`,
      `  enable_dns_support   = ${vpc.enableDnsSupport}`,
      `  enable_dns_hostnames = ${vpc.enableDnsHostnames}`,
      '',
      '  tags = {',
      `    Name = "${vpc.name}"`,
      ...vpc.tags.map((t) => `    ${t.key} = "${t.value}"`),
      '  }',
      '}',
      '',
    ];

    // Subnets
    subnets.forEach((subnet) => {
      lines.push(`# Subnet: ${subnet.name}`);
      lines.push(`resource "aws_subnet" "${subnet.name.replace(/-/g, '_')}" {`);
      lines.push(`  vpc_id                  = aws_vpc.${vpc.name.replace(/-/g, '_')}.id`);
      lines.push(`  cidr_block              = "${subnet.cidrBlock}"`);
      lines.push(`  availability_zone       = "${subnet.availabilityZone}"`);
      lines.push(`  map_public_ip_on_launch = ${subnet.mapPublicIpOnLaunch}`);
      lines.push('');
      lines.push('  tags = {');
      lines.push(`    Name = "${subnet.name}"`);
      lines.push(`    Type = "${subnet.isPublic ? 'Public' : 'Private'}"`);
      lines.push('  }');
      lines.push('}');
      lines.push('');
    });

    // Internet Gateway
    if (routing.internetGateway.enabled) {
      lines.push('# Internet Gateway');
      lines.push(`resource "aws_internet_gateway" "${routing.internetGateway.name.replace(/-/g, '_')}" {`);
      lines.push(`  vpc_id = aws_vpc.${vpc.name.replace(/-/g, '_')}.id`);
      lines.push('');
      lines.push('  tags = {');
      lines.push(`    Name = "${routing.internetGateway.name}"`);
      lines.push('  }');
      lines.push('}');
      lines.push('');
    }

    // NAT Gateways
    routing.natGateways.forEach((nat) => {
      const subnet = subnets.find((s) => s.id === nat.subnetId);
      lines.push(`# NAT Gateway: ${nat.name}`);
      lines.push(`resource "aws_eip" "${nat.name.replace(/-/g, '_')}_eip" {`);
      lines.push('  domain = "vpc"');
      lines.push('}');
      lines.push('');
      lines.push(`resource "aws_nat_gateway" "${nat.name.replace(/-/g, '_')}" {`);
      lines.push(`  allocation_id = aws_eip.${nat.name.replace(/-/g, '_')}_eip.id`);
      if (subnet) {
        lines.push(`  subnet_id     = aws_subnet.${subnet.name.replace(/-/g, '_')}.id`);
      }
      lines.push('');
      lines.push('  tags = {');
      lines.push(`    Name = "${nat.name}"`);
      lines.push('  }');
      lines.push('}');
      lines.push('');
    });

    // Security Groups
    securityGroups.forEach((sg) => {
      lines.push(`# Security Group: ${sg.name}`);
      lines.push(`resource "aws_security_group" "${sg.name.replace(/-/g, '_')}" {`);
      lines.push(`  name        = "${sg.name}"`);
      lines.push(`  description = "${sg.description || sg.name}"`);
      lines.push(`  vpc_id      = aws_vpc.${vpc.name.replace(/-/g, '_')}.id`);
      lines.push('');

      sg.ingressRules.forEach((rule) => {
        lines.push('  ingress {');
        lines.push(`    from_port   = ${rule.fromPort}`);
        lines.push(`    to_port     = ${rule.toPort}`);
        lines.push(`    protocol    = "${rule.protocol}"`);
        lines.push(`    cidr_blocks = ["${rule.source}"]`);
        if (rule.description) {
          lines.push(`    description = "${rule.description}"`);
        }
        lines.push('  }');
        lines.push('');
      });

      sg.egressRules.forEach((rule) => {
        lines.push('  egress {');
        lines.push(`    from_port   = ${rule.fromPort}`);
        lines.push(`    to_port     = ${rule.toPort}`);
        lines.push(`    protocol    = "${rule.protocol}"`);
        lines.push(`    cidr_blocks = ["${rule.source}"]`);
        if (rule.description) {
          lines.push(`    description = "${rule.description}"`);
        }
        lines.push('  }');
        lines.push('');
      });

      lines.push('  tags = {');
      lines.push(`    Name = "${sg.name}"`);
      lines.push('  }');
      lines.push('}');
      lines.push('');
    });

    return lines.join('\n');
  }, [vpc, subnets, routing, securityGroups]);

  // Copy to clipboard
  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(terraformCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [terraformCode]);

  // Render validation icon
  const renderIcon = (severity: 'error' | 'warning' | 'info') => {
    switch (severity) {
      case 'error':
        return <ErrorIcon color="error" />;
      case 'warning':
        return <WarningIcon color="warning" />;
      case 'info':
        return <InfoIcon color="info" />;
    }
  };

  return (
    <Box>
      <Typography variant="h6" gutterBottom>
        Review & Validate
      </Typography>
      <Typography variant="body2" color="text.secondary" paragraph>
        Review your network configuration and resolve any issues before deployment.
      </Typography>

      {/* Validation Status */}
      <Paper sx={{ p: 2, mb: 2 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
          {validationResult.isValid ? (
            <>
              <SuccessIcon color="success" sx={{ fontSize: 48 }} />
              <Box>
                <Typography variant="h6" color="success.main">
                  Configuration Valid
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Your network configuration is ready for deployment.
                </Typography>
              </Box>
            </>
          ) : (
            <>
              <ErrorIcon color="error" sx={{ fontSize: 48 }} />
              <Box>
                <Typography variant="h6" color="error.main">
                  Configuration Has Issues
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Please resolve the errors below before deploying.
                </Typography>
              </Box>
            </>
          )}
          <Box sx={{ flex: 1 }} />
          <Box sx={{ display: 'flex', gap: 1 }}>
            <Chip
              icon={<ErrorIcon />}
              label={`${validationResult.errors.length} Errors`}
              color={validationResult.errors.length > 0 ? 'error' : 'default'}
              variant="outlined"
            />
            <Chip
              icon={<WarningIcon />}
              label={`${validationResult.warnings.length} Warnings`}
              color={validationResult.warnings.length > 0 ? 'warning' : 'default'}
              variant="outlined"
            />
            <Chip
              icon={<InfoIcon />}
              label={`${validationResult.info.length} Suggestions`}
              variant="outlined"
            />
          </Box>
        </Box>
      </Paper>

      {/* Errors */}
      {validationResult.errors.length > 0 && (
        <Alert severity="error" sx={{ mb: 2 }}>
          <AlertTitle>Errors ({validationResult.errors.length})</AlertTitle>
          <List dense>
            {validationResult.errors.map((error, i) => (
              <ListItem
                key={i}
                secondaryAction={
                  error.fix && onFix ? (
                    <Button size="small" startIcon={<FixIcon />} onClick={() => onFix(error)}>
                      Fix
                    </Button>
                  ) : null
                }
              >
                <ListItemIcon>{renderIcon('error')}</ListItemIcon>
                <ListItemText primary={error.message} secondary={error.path} />
              </ListItem>
            ))}
          </List>
        </Alert>
      )}

      {/* Warnings */}
      {validationResult.warnings.length > 0 && (
        <Alert severity="warning" sx={{ mb: 2 }}>
          <AlertTitle>Warnings ({validationResult.warnings.length})</AlertTitle>
          <List dense>
            {validationResult.warnings.map((warning, i) => (
              <ListItem
                key={i}
                secondaryAction={
                  warning.fix && onFix ? (
                    <Button size="small" startIcon={<FixIcon />} onClick={() => onFix(warning)}>
                      Fix
                    </Button>
                  ) : null
                }
              >
                <ListItemIcon>{renderIcon('warning')}</ListItemIcon>
                <ListItemText primary={warning.message} secondary={warning.path} />
              </ListItem>
            ))}
          </List>
        </Alert>
      )}

      {/* Info/Suggestions */}
      {validationResult.info.length > 0 && (
        <Alert severity="info" sx={{ mb: 2 }}>
          <AlertTitle>Best Practice Suggestions ({validationResult.info.length})</AlertTitle>
          <List dense>
            {validationResult.info.map((info, i) => (
              <ListItem key={i}>
                <ListItemIcon>{renderIcon('info')}</ListItemIcon>
                <ListItemText primary={info.message} />
              </ListItem>
            ))}
          </List>
        </Alert>
      )}

      {/* Configuration Summary */}
      <Accordion defaultExpanded>
        <AccordionSummary expandIcon={<ExpandMoreIcon />}>
          <Typography variant="subtitle1" fontWeight={500}>
            Configuration Summary
          </Typography>
        </AccordionSummary>
        <AccordionDetails>
          <Table size="small">
            <TableBody>
              <TableRow>
                <TableCell component="th" sx={{ fontWeight: 500 }}>VPC CIDR</TableCell>
                <TableCell>{stats.vpcCidr}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell component="th" sx={{ fontWeight: 500 }}>Subnets</TableCell>
                <TableCell>
                  {stats.totalSubnets} ({stats.publicSubnets} public, {stats.privateSubnets} private)
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell component="th" sx={{ fontWeight: 500 }}>Available IPs</TableCell>
                <TableCell>{stats.totalIPs.toLocaleString()}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell component="th" sx={{ fontWeight: 500 }}>Internet Gateway</TableCell>
                <TableCell>
                  <Chip
                    size="small"
                    label={stats.hasIGW ? 'Enabled' : 'Disabled'}
                    color={stats.hasIGW ? 'success' : 'default'}
                    variant="outlined"
                  />
                </TableCell>
              </TableRow>
              <TableRow>
                <TableCell component="th" sx={{ fontWeight: 500 }}>NAT Gateways</TableCell>
                <TableCell>{stats.natCount}</TableCell>
              </TableRow>
              <TableRow>
                <TableCell component="th" sx={{ fontWeight: 500 }}>Security Groups</TableCell>
                <TableCell>{stats.sgCount} ({stats.ruleCount} rules)</TableCell>
              </TableRow>
              <TableRow>
                <TableCell component="th" sx={{ fontWeight: 500 }}>Estimated Monthly Cost</TableCell>
                <TableCell>
                  {stats.natCount > 0 ? (
                    <Typography variant="body2">
                      ~${stats.estimatedCost.toFixed(2)}/month (NAT Gateway only)
                    </Typography>
                  ) : (
                    <Typography variant="body2" color="text.secondary">
                      No recurring infrastructure costs
                    </Typography>
                  )}
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </AccordionDetails>
      </Accordion>

      {/* Terraform Preview */}
      <Box sx={{ mt: 2 }}>
        <Button
          variant="outlined"
          startIcon={<CodeIcon />}
          onClick={() => setTerraformDialogOpen(true)}
        >
          Preview Terraform
        </Button>
      </Box>

      {/* Terraform Dialog */}
      <Dialog
        open={terraformDialogOpen}
        onClose={() => setTerraformDialogOpen(false)}
        maxWidth="md"
        fullWidth
      >
        <DialogTitle>
          Terraform Preview
          <Tooltip title={copied ? 'Copied!' : 'Copy to clipboard'}>
            <IconButton onClick={handleCopy} sx={{ ml: 1 }}>
              <CopyIcon />
            </IconButton>
          </Tooltip>
        </DialogTitle>
        <DialogContent>
          <Alert severity="info" sx={{ mb: 2 }}>
            This is a preview. The actual deployment will generate complete, production-ready Terraform code.
          </Alert>
          <Paper
            sx={{
              p: 2,
              bgcolor: 'grey.900',
              color: 'grey.100',
              fontFamily: 'monospace',
              fontSize: 12,
              overflow: 'auto',
              maxHeight: 400,
              whiteSpace: 'pre',
            }}
          >
            {terraformCode}
          </Paper>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setTerraformDialogOpen(false)}>Close</Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}

export default NetworkValidationStep;
